version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: notes-mysql
    restart: always
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script-db/ddl-script.sql:/docker-entrypoint-initdb.d/ddl-script.sql:ro
      - ./script-db/dml-script.sql:/docker-entrypoint-initdb.d/dml-script.sql:ro

  app:
    build: .
    container_name: notes-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notesdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  db_data:
